### ISSUE TITLE
fail to build from source - SDL related

### ISSUE THREAD

**Issue by StarryWisdom** [daid/SeriousProton2#6]
/home/starry/EE/EEOne/SeriousProton2/src/engine.cpp: In constructor ‘sp::Engine::Engine()’:
/home/starry/EE/EEOne/SeriousProton2/src/engine.cpp:70:17: error: ‘SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH’ was not declared in this scope
   70 |     SDL_SetHint(SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH, "1");

I think looking at release notes its SDL2 >=2.10

> Removed SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH (replaced by SDL_HINT_MOUSE_TOUCH_EVENTS and SDL_HINT_TOUCH_MOUSE_EVENTS)
> SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH=1, should be replaced by setting both previous hints to 0.
> SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH=0, should be replaced by setting both previous hints to 1.

**Comment by daid** [comment]
Actually, it's introduced in 2.0.4: https://github.com/spurious/SDL-mirror/blob/release-2.0.4/include/SDL_hints.h
But, 2.0.6 introduced SDL_HINT_TOUCH_MOUSE_EVENTS
And 2.0.10 seems to have removed the SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH in favor of that new one.
